source 'https://rubygems.org'


gem 'rails', '6.1.7.3'
gem 'sqlite3'
gem 'haml', '~> 5.0.0'
gem 'sass-rails', '~> 6.0', '>= 6.0.0'
gem 'uglifier', '>= 2.7.2'
gem 'coffee-rails', '~> 4.2.2'
gem 'jquery-rails', '>= 4.4.0'
gem 'turbolinks', '>= 5.0.0'
gem 'jbuilder', '~> 2.6', '>= 2.6.4'
gem 'sdoc', '~> 1.0.0', group: :doc
gem 'better_errors', '~> 2.8.0'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.1', '>= 2.1.3'
  gem 'spring'
  gem 'rspec-rails', '>= 3.5.0'
end

group :test do
    gem 'capybara'
end

