source 'https://rubygems.org'


gem 'rails', '5.0.0'
gem 'sqlite3'
gem 'haml', '~> 4.0.6'
gem 'sass-rails', '~> 5.0', '>= 5.0.5'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.1'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'better_errors', '~> 2.1.1'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.1', '>= 2.1.2'
  gem 'spring'
  gem 'rspec-rails', '>= 3.5.0'
end

group :test do
    gem 'capybara'
end

